# Tristan Jones
# Non-Rigid 3D Shape Registration using Thin Plate Splines
# Adapted for TotalSegmentator organ segmentations

#imports
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import nibabel as nib
from scipy.ndimage import label, center_of_mass
from scipy.spatial import cKDTree

# 3/30/26
# This file is quite old and originally was based off another file where the TPS was originally tested to essentially map one sphere/random shape onto another sphere/random shape 
# as such the currenty TPS implementation is very flawsed and I will need to work on making sure that theres better implemention steps being done here. 

# Some things were made with claude so I will point those out where relevant. 

# Generally what does this file do? 
# This file essentially takes the output from testing_totl_segmentator.py which is all the segments in the data folder. 
# It then does a prealignment, then implement the TPS based on anatomical landmarks outputs as transformed_{ID1}_to_{ID2}.nii.gz

#again some def generated by claude but ill try and showcase where. 





class NonRigidMapper3D:
    """
    3D non-rigid shape registration using Thin Plate Splines.
    Designed to work with medical imaging segmentations.
    """
    

    # this is really jsut initialization stuff
    def __init__(self, source_points, target_points):
        """
        Initialize with source (deformed) and target (baseline) points in 3D.
        
        Args:
            source_points: numpy array of shape (N, 3) - the points to transform
            target_points: numpy array of shape (N, 3) - the target points to match
        """
        self.source_points = np.array(source_points)
        self.target_points = np.array(target_points)
        
        if len(self.source_points) != len(self.target_points):
            raise ValueError("Source and target shapes must have the same number of points")
        
        if self.source_points.shape[1] != 3 or self.target_points.shape[1] != 3:
            raise ValueError("Points must be 3D (N, 3)")
        
        # Pre-compute the TPS kernel matrix for efficiency
        self.K = self._compute_tps_kernel_matrix()



    #This is not currently in use this is an old plotting thing that I was using for visualization probably should just remove this.
    def visualize_point_matching(self):  
        """
        Visualize how source and target points are matched in 3D.
        """
        fig = plt.figure(figsize=(18, 12))
        
        # 3D plot: Point correspondence
        ax1 = fig.add_subplot(221, projection='3d')
        ax1.set_title('Point Correspondence Vectors (every 5th point)', fontsize=12, fontweight='bold')
        ax1.scatter(self.source_points[:, 0], self.source_points[:, 1], self.source_points[:, 2],
                   c='red', s=30, alpha=0.6, label='Source')
        ax1.scatter(self.target_points[:, 0], self.target_points[:, 1], self.target_points[:, 2],
                   c='blue', s=30, alpha=0.6, label='Target')
        
        n = len(self.source_points)
        for i in range(0, n, max(1, n//40)):
            ax1.quiver(self.source_points[i, 0], self.source_points[i, 1], self.source_points[i, 2],
                      self.target_points[i, 0] - self.source_points[i, 0],
                      self.target_points[i, 1] - self.source_points[i, 1],
                      self.target_points[i, 2] - self.source_points[i, 2],
                      color='green', arrow_length_ratio=0.3, alpha=0.6)
        
        ax1.set_xlabel('X')
        ax1.set_ylabel('Y')
        ax1.set_zlabel('Z')
        ax1.legend(fontsize=10)
        
        # Distance plot
        ax3 = fig.add_subplot(223)
        ax3.set_title('Distance Between Corresponding Points', fontsize=12, fontweight='bold')
        distances = np.linalg.norm(self.source_points - self.target_points, axis=1)
        ax3.plot(distances, 'g-', linewidth=2)
        ax3.set_xlabel('Point Index', fontsize=10)
        ax3.set_ylabel('Distance', fontsize=10)
        ax3.grid(True, alpha=0.3)
        ax3.axhline(y=np.mean(distances), color='r', linestyle='--', linewidth=2,
                   label=f'Mean: {np.mean(distances):.2f}')
        ax3.axhline(y=np.median(distances), color='orange', linestyle='--', linewidth=2,
                   label=f'Median: {np.median(distances):.2f}')
        ax3.legend(fontsize=10)
        
        # Displacement magnitude histogram
        ax4 = fig.add_subplot(224)
        ax4.set_title('Displacement Vector Magnitudes', fontsize=12, fontweight='bold')
        n_bins = max(5, min(30, len(distances)))
        ax4.hist(distances, bins=n_bins, color='green', alpha=0.7, edgecolor='black')
        ax4.axvline(x=np.mean(distances), color='r', linestyle='--', linewidth=2,
                   label=f'Mean: {np.mean(distances):.2f}')
        ax4.set_xlabel('Displacement Distance', fontsize=10)
        ax4.set_ylabel('Count', fontsize=10)
        ax4.legend(fontsize=10)
        ax4.grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()
        
        print(f"\n=== Point Matching Statistics ===")
        print(f"Mean point-to-point distance: {np.mean(distances):.2f}")
        print(f"Median point-to-point distance: {np.median(distances):.2f}")
        print(f"Max point-to-point distance: {np.max(distances):.2f}")
        print(f"Min point-to-point distance: {np.min(distances):.2f}")
        
        large_displacements = np.where(distances > 2 * np.median(distances))[0]
        if len(large_displacements) > 0:
            print(f"\n⚠️  WARNING: {len(large_displacements)} points have unusually large displacements!")
    

    # TPS kernel essentailly defines how influence spreads so if you have 5 points nearby one another in a line
    # does/how much point 1 influence the impact of point 5 and other points around it because essentially each point
    # "bends space" so to speak but we can predefine how much each one does that. 
    def _tps_kernel(self, r):
        """Compute the TPS kernel function for 3D: U(r) = r"""
        # this is for the thin plate spline kernel in 3D
        mask = r != 0
        k = np.zeros_like(r)
        k[mask] = r[mask]
        return k
    
    # kernel matrix essentially determines how "inter-related" each point is to one another This was signifigantly
    # more important before because of the way TPS works so will need to update landmarks to maybe somehow find more
    # methods of what makes a corresponding point when its not specifically at the ends of the shape. 
    # Essentially though this is the matrix NxN where entry i,j is the kernel value between source  control point 
    # i and source control point j. It encodes how "related" every pair of control points is based on their distance.
    def _compute_tps_kernel_matrix(self):
        """Compute the kernel matrix for the source points."""
        # pairwise distances
        diff = self.source_points[:, np.newaxis, :] - self.source_points[np.newaxis, :, :]
        r = np.sqrt((diff**2).sum(axis=2))
        return self._tps_kernel(r)
    


    # this one is semi complicated and It would be best to visually show how this works, but it essnetially solves 
    #the TPS linear system of equations, alpha is regularization where higher will be smoother but less accurate fit. 
    # very old may need updating but again large issue is with the manor of finding corresponding points lol
    def find_transformation(self, alpha=0.1):
        """Find the non-rigid transformation using 3D TPS."""
        n = len(self.source_points)
        P = np.column_stack([np.ones(n), self.source_points])
        
        L = np.block([
            [self.K + alpha * np.eye(n), P],
            [P.T, np.zeros((4, 4))]
        ])
        
        Y = np.vstack([self.target_points, np.zeros((4, 3))])
        
        try:
            coefficients = np.linalg.solve(L, Y)
        except np.linalg.LinAlgError:
            coefficients = np.linalg.lstsq(L, Y, rcond=None)[0]
        
        return coefficients[:n], coefficients[n:]
    

    # I may need to update this or actually just update the specific ways in which I am grabbing "corresponding points"
    # currently as of 3/30/26 this works as intended but the intention is clearly flawed lol 

    def transform_points(self, points, coefficients, batch_size=5000):
        """Apply the 3D TPS transformation to a set of points.
        
        Args:
            points: Array of points to transform (N, 3)
            coefficients: TPS coefficients (w, a)
            batch_size: Number of points to process at once to avoid memory issues
        
        Returns:
            Transformed points (N, 3)
        """
        w, a = coefficients
        n_points = len(points)
        
        # 3/15/26 needed to add this batching to the function because it wasnt working otherwise
        # issue being huge overhead on memory usage, possible to use without this or maybe add clause
        # later to only use batch if mem on comp is inssufficient 
        if n_points > batch_size:
            transformed = np.zeros_like(points)
            n_batches = (n_points + batch_size - 1) // batch_size
            print(f"  Processing in {n_batches} batches...")
            
            for batch_idx, i in enumerate(range(0, n_points, batch_size)):
                batch_end = min(i + batch_size, n_points)
                batch_points = points[i:batch_end]
                
                # Compute for this batch
                diff = batch_points[:, np.newaxis, :] - self.source_points[np.newaxis, :, :]
                r = np.sqrt((diff**2).sum(axis=2))
                K = self._tps_kernel(r)
                
                P = np.column_stack([np.ones(len(batch_points)), batch_points])
                transformed[i:batch_end] = K @ w + P @ a
                
                # Progress indicator every 10 batches
                if (batch_idx + 1) % 10 == 0 or (batch_idx + 1) == n_batches:
                    print(f"    Batch {batch_idx + 1}/{n_batches} complete", flush=True)
            
            return transformed
        else:
            # For small arrays, process all at once
            diff = points[:, np.newaxis, :] - self.source_points[np.newaxis, :, :]
            r = np.sqrt((diff**2).sum(axis=2))
            K = self._tps_kernel(r)
            
            P = np.column_stack([np.ones(len(points)), points])
            transformed = K @ w + P @ a
            
            return transformed
    

# 3/30/26 entirely changed every aspect of this class over the past week or so generally I think that this class is 
# probably like at least 90% generated by claude based on old work of mine and additionally based on my ideas of a new method of 
# implementation. I'll run through exactly whats going on in this file though. 

class TotalSegmentatorRegistration:
    """
    Registers organ segmentations from TotalSegmentator using non-rigid 3D TPS.
    """
    #initiallizes
    def __init__(self, organ_name="liver"):
        """
        Initialize the registration system.
        
        Args:
            organ_name: Name of the organ to register (e.g., 'liver', 'pancreas', 'kidney')
        """
        self.organ_name = organ_name
        self.mapper = None
        self.reference_segmentation = None
        self.source_segmentation = None
        self.prealign_R = None
        self.prealign_t_src = None
        self.prealign_t_ref = None
        self.prealign_src_aff = None
        self.prealign_ref_aff = None
        self.ref_shape = None
        

    # loads a nifti file and returns the voxel array and affine matrix     
    def load_segmentation_from_file(self, filepath):
        """
        Load a segmentation from a NIfTI file.
        
        Args:
            filepath: Path to .nii or .nii.gz file
            
        Returns:
            numpy array of segmentation data
        """
        print(f"Loading segmentation from {filepath}...")
        try:
            img  = nib.load(filepath)
            data = img.get_fdata()
            print(f"  Shape: {data.shape}, spacing: "
                  f"{np.sqrt((img.affine[:3,:3]**2).sum(axis=0)).round(2)} mm")
            return data, img.affine
        except Exception as e:
            print(f"ERROR loading file: {e}")
            raise
    

    # uses a sobel edge filter to find the boundary vosels of an organ mask (the outside)
    # this is I'm pretty sure mostly old code from before in the 3d case but may have been updated by claude
    # I'd need to 100% double check I really had a lot of things that I just scrapped entirely lol
    # but essentially this looks at the gradient of image intensity using convolution kernels pretty basic image processing 
    # edge detection stuff
    def extract_organ_surface(self, segmentation, organ_label=1, downsample=10):
        """
        Extract surface points from a segmentation volume.
        
        Args:
            segmentation: 3D binary or labeled array
            organ_label: Label value for the organ of interest (default 1)
            downsample: Sample every Nth voxel for faster processing
            
        Returns:
            numpy array of shape (N, 3) with surface voxel coordinates
        """
        print(f"Extracting surface from organ label {organ_label}...")
        
        # Threshold segmentation to get binary mask
        binary_mask = (segmentation == organ_label).astype(np.uint8)
        
        if np.sum(binary_mask) == 0:
            raise ValueError(f"No voxels found with label {organ_label}")
        
        # Find boundary voxels (where mask transitions from 0 to 1)
        from scipy.ndimage import sobel
        
        # Apply Sobel filter to find edges
        edges = sobel(binary_mask)
        edge_voxels = np.argwhere(edges > 0)
        
        # Downsample for faster processing
        if downsample > 1:
            edge_voxels = edge_voxels[::downsample]
        
        print(f"  Extracted {len(edge_voxels)} surface voxels")
        
        return edge_voxels.astype(np.float32)
    


    # this function was made by claude 100% I was asking claude how do I even define what is a corresponding point?
    # then it gave me a few ideas and the most strenuous but also most accurate would be doing this 
    # so I prompted it: Can you generate me a function that gets anatomical landmarks [list of relevant ones] 
    # thats basically what happened then there were additions to this function as time went on 
    def extract_anatomical_landmarks(self, liver_seg, portal_vein_seg=None,
                                  segment_segs=None, hepatic_vein_seg=None,
                                  organ_label=1, portal_label=1,
                                  cluster_radius=5,
                                  return_representative_points=False):
        """
        Extract anatomical landmark CLUSTERS from four sources, in order:

          1. Couinaud liver segments (seg 1-8) — most anatomically stable
          2. Portal vein branch points — right branch, left branch, superior entry
          3. Hepatic veins — right, middle, left branch centroids + IVC confluence
          4. Liver geometry — centroid + 6 extremal surface tips

        Correspondence is by anatomical identity: index 0 is always segment-1
        centroid, index 8 is always portal-right-branch, etc. on both scans.
        This is what makes these 'corresponding points' for TPS.

        Args:
            liver_seg:     3-D array, whole-liver binary mask (label == organ_label)
            portal_vein_seg: 3-D array, portal+splenic vein mask (optional)
            segment_segs:  dict {1: array, ..., 8: array}, each a binary mask for
                           one Couinaud segment (optional)
            hepatic_vein_seg: 3-D array, hepatic vein mask (optional)
            organ_label:   voxel value for liver in liver_seg
            portal_label:  voxel value for portal vein in portal_vein_seg
            cluster_radius: starting ball radius in voxels (auto-expands if needed)
            return_representative_points: if True return one point per landmark
                           (for visualization) instead of full clusters
        """

        def resolve_nonzero_label(seg, requested_label, name):
            unique_labels = np.unique(seg)
            nonzero_labels = unique_labels[unique_labels > 0]
            if len(nonzero_labels) == 0:
                raise ValueError(f"No non-zero voxels in {name}")
            matches = np.isclose(nonzero_labels, requested_label)
            if np.any(matches):
                return float(nonzero_labels[np.where(matches)[0][0]])
            chosen = float(nonzero_labels[0])
            print(f"  Label {requested_label} not found in {name}; using {chosen}")
            return chosen

        # Resolve liver label and get all liver voxels.
        actual_organ_label = resolve_nonzero_label(liver_seg, organ_label, "liver")
        liver_voxels = np.argwhere(
            np.isclose(liver_seg, actual_organ_label)
        ).astype(np.float32)
        print(f"  Organ label {actual_organ_label}: {len(liver_voxels):,} voxels")

        # So essentially instead of just taking a singular point at a defined location i wanted to take a cluster of
        # points around a location as the specific points that are representative of the 
        def ball_around(center, all_voxels, radius, cap=50):
            dists = np.linalg.norm(all_voxels - center, axis=1)
            nearby = all_voxels[dists <= radius]
            r = radius
            while len(nearby) < 10 and r < radius * 8:
                r *= 1.5
                nearby = all_voxels[dists <= r]
            if len(nearby) == 0:
                nearby = all_voxels[:1]  # degenerate fallback: use any point
            # Always output exactly cap points (downsample or oversample as needed)
            idx = np.random.choice(len(nearby), cap, replace=len(nearby) < cap)
            return nearby[idx], r

        all_clusters = []
        representative_points = []

        def add_landmark(center, name, voxel_pool=None):
            pool = liver_voxels if voxel_pool is None else voxel_pool
            cluster, actual_r = ball_around(center, pool, cluster_radius)
            all_clusters.append(cluster)
            representative_points.append(center.copy())
            if actual_r > cluster_radius:
                print(f"  {name}: expanded radius to {actual_r:.1f}, "
                      f"{len(cluster)} pts")
            else:
                print(f"  {name}: {len(cluster)} pts at radius {actual_r:.1f}")

        # ------------------------------------------------------------------
        # Source 1: Couinaud liver segment centroids (segments 1-8)
        # ------------------------------------------------------------------
        if segment_segs is not None:
            print("\n  [Source 1] Couinaud segment centroids:")
            liver_centroid = liver_voxels.mean(axis=0)
            for seg_idx in range(1, 9):
                seg_arr = segment_segs.get(seg_idx)
                if seg_arr is not None:
                    seg_voxels = np.argwhere(seg_arr > 0).astype(np.float32)
                else:
                    seg_voxels = np.empty((0, 3), dtype=np.float32)

                if len(seg_voxels) >= 10:
                    centroid = seg_voxels.mean(axis=0)
                    add_landmark(centroid, f"Segment {seg_idx} centroid", seg_voxels)
                else:
                    # Fallback: use liver centroid so landmark count stays fixed.
                    print(f"  Segment {seg_idx}: too few voxels ({len(seg_voxels)}), "
                          f"using liver centroid as fallback")
                    add_landmark(liver_centroid, f"Segment {seg_idx} fallback")

        # ------------------------------------------------------------------
        # Source 2: Portal vein branch points
        #   right branch  = centroid of voxels in the right (high-X) half
        #   left branch   = centroid of voxels in the left  (low-X) half
        #   superior entry= centroid of voxels in the top   (high-Z) third
        # ------------------------------------------------------------------
        if portal_vein_seg is not None:
            print("\n  [Source 2] Portal vein branch points:")
            actual_portal_label = resolve_nonzero_label(
                portal_vein_seg, portal_label, "portal"
            )
            portal_voxels = np.argwhere(
                np.isclose(portal_vein_seg, actual_portal_label)
            ).astype(np.float32)

            if len(portal_voxels) >= 20:
                x_median = np.median(portal_voxels[:, 0])
                z_thresh = np.percentile(portal_voxels[:, 2], 67)

                right_pv = portal_voxels[portal_voxels[:, 0] >= x_median]
                left_pv  = portal_voxels[portal_voxels[:, 0] <  x_median]
                sup_pv   = portal_voxels[portal_voxels[:, 2] >= z_thresh]

                for name, subset in [
                    ("PV right branch",   right_pv),
                    ("PV left branch",    left_pv),
                    ("PV superior entry", sup_pv),
                ]:
                    if len(subset) > 0:
                        centroid = subset.mean(axis=0)
                        add_landmark(centroid, name, portal_voxels)
                    else:
                        centroid = portal_voxels.mean(axis=0)
                        add_landmark(centroid, f"{name} (fallback)", portal_voxels)
            else:
                print(f"  Portal vein: too few voxels ({len(portal_voxels)}), skipped")

        # ------------------------------------------------------------------
        # Source 3: Hepatic vein landmarks
        #   right HV  = centroid of voxels in the right (high-X) third
        #   middle HV = centroid of voxels in the central X third
        #   left HV   = centroid of voxels in the left (low-X) third
        #   IVC confluence = centroid of voxels in the superior (high-Z) quarter
        # ------------------------------------------------------------------
        if hepatic_vein_seg is not None:
            print("\n  [Source 3] Hepatic vein landmarks:")
            hv_voxels = np.argwhere(hepatic_vein_seg > 0).astype(np.float32)
            if len(hv_voxels) >= 20:
                x_lo  = np.percentile(hv_voxels[:, 0], 33)
                x_hi  = np.percentile(hv_voxels[:, 0], 67)
                z_top = np.percentile(hv_voxels[:, 2], 75)

                right_hv  = hv_voxels[hv_voxels[:, 0] >  x_hi]
                middle_hv = hv_voxels[(hv_voxels[:, 0] >= x_lo) & (hv_voxels[:, 0] <= x_hi)]
                left_hv   = hv_voxels[hv_voxels[:, 0] <  x_lo]
                ivc_conf  = hv_voxels[hv_voxels[:, 2] >= z_top]

                for name, subset in [
                    ("HV right branch",    right_hv),
                    ("HV middle branch",   middle_hv),
                    ("HV left branch",     left_hv),
                    ("HV IVC confluence",  ivc_conf),
                ]:
                    if len(subset) > 0:
                        centroid = subset.mean(axis=0)
                        add_landmark(centroid, name, hv_voxels)
                    else:
                        centroid = hv_voxels.mean(axis=0)
                        add_landmark(centroid, f"{name} (fallback)", hv_voxels)
            else:
                print(f"  Hepatic veins: too few voxels ({len(hv_voxels)}), skipped")

        # ------------------------------------------------------------------
        # Source 4: Liver geometry — centroid + 6 extremal surface tips
        # ------------------------------------------------------------------
        print("\n  [Source 4] Liver geometry tips:")
        liver_centroid = liver_voxels.mean(axis=0)
        add_landmark(liver_centroid, "Liver centroid")

        extremes = [
            ("Superior tip  (max Z)", liver_voxels[liver_voxels[:, 2].argmax()]),
            ("Inferior tip  (min Z)", liver_voxels[liver_voxels[:, 2].argmin()]),
            ("Right lobe    (max X)", liver_voxels[liver_voxels[:, 0].argmax()]),
            ("Left lobe     (min X)", liver_voxels[liver_voxels[:, 0].argmin()]),
            ("Anterior tip  (max Y)", liver_voxels[liver_voxels[:, 1].argmax()]),
            ("Posterior tip (min Y)", liver_voxels[liver_voxels[:, 1].argmin()]),
        ]
        for name, tip in extremes:
            add_landmark(tip, name)

        # ------------------------------------------------------------------
        if return_representative_points:
            return np.vstack(representative_points).astype(np.float32)

        landmarks = np.vstack(all_clusters)
        print(f"\n  Total control points: {len(landmarks)}")
        return landmarks


    # Prompt need to help figure out how to get the two shapes in the same relative plane so they are relatively aligned
    # can you write me a function that can prealign them based off the landmarks 
    def _prealign_landmarks(self, src_landmarks, ref_landmarks,
                            src_affine, ref_affine,
                            n_segment_landmarks=8):
        """
        Pre-align source landmarks to reference using Procrustes on Couinaud
        segment centroids, working in mm world coordinates via the NIfTI affine.

        This correctly handles different voxel spacings and grid sizes across
        patients — all alignment math happens in physical mm space, then results
        are converted back to reference voxel space.

        Args:
            src_landmarks:       (N, 3) source control points in voxel coords
            ref_landmarks:       (N, 3) reference control points in voxel coords
            src_affine:          (4, 4) affine matrix from source NIfTI header
            ref_affine:          (4, 4) affine matrix from reference NIfTI header
            n_segment_landmarks: how many leading landmarks are segment centroids
        """
        def voxels_to_mm(voxels, affine):
            ones  = np.ones((len(voxels), 1))
            vox_h = np.hstack([voxels, ones])
            mm_h  = (affine @ vox_h.T).T
            return mm_h[:, :3]

        def mm_to_voxels(mm_pts, affine):
            inv_affine = np.linalg.inv(affine)
            ones  = np.ones((len(mm_pts), 1))
            mm_h  = np.hstack([mm_pts, ones])
            vox_h = (inv_affine @ mm_h.T).T
            return vox_h[:, :3]

        # Convert everything to mm world space
        src_mm = voxels_to_mm(src_landmarks, src_affine)
        ref_mm = voxels_to_mm(ref_landmarks, ref_affine)

        # Use only the segment centroid landmarks for alignment
        src_seg_mm = src_mm[:n_segment_landmarks]
        ref_seg_mm = ref_mm[:n_segment_landmarks]

        # Step 1: Translation — align centroids
        src_center = src_seg_mm.mean(axis=0)
        ref_center = ref_seg_mm.mean(axis=0)
        src_seg_c  = src_seg_mm - src_center
        ref_seg_c  = ref_seg_mm - ref_center

        # Step 2: SVD Procrustes rotation
        H   = src_seg_c.T @ ref_seg_c
        U, _, Vt = np.linalg.svd(H)
        R   = Vt.T @ U.T
        if np.linalg.det(R) < 0:
            Vt[-1, :] *= -1
            R = Vt.T @ U.T

        # Step 3: Apply to ALL source landmarks in mm space
        src_all_c      = src_mm - src_center
        src_aligned_mm = (R @ src_all_c.T).T + ref_center

        # Step 4: Convert aligned mm coordinates back to reference voxel space
        src_aligned_vox = mm_to_voxels(src_aligned_mm, ref_affine)

        # Report quality on segment landmarks only (in mm — clinically meaningful)
        seg_aligned_mm = src_aligned_mm[:n_segment_landmarks]
        residuals_mm   = np.linalg.norm(seg_aligned_mm - ref_seg_mm, axis=1)

        print(f"\n  Pre-alignment quality (segment centroids):")
        for i, d in enumerate(residuals_mm):
            print(f"    Seg {i+1}: {d:.1f} mm residual")
        print(f"    Mean residual: {residuals_mm.mean():.1f} mm")
        print(f"    Max residual:  {residuals_mm.max():.1f} mm")
        print(f"    Translation:   {(ref_center - src_center).round(1)} mm")

        return src_aligned_vox, R, src_center, ref_center, src_affine, ref_affine


    # writen by claude as a part of one of these other prompts 
    def register(self, data_dir, reference_id, source_id,
                 organ_label=1, alpha=0.05):
        """
        Register source patient to reference patient using anatomical landmarks
        + mm-space Procrustes pre-alignment + TPS.

        Pipeline:
            1. Load all structures for both patients from data_dir/<id>/
            2. Extract anatomical landmarks from both scans
            3. Pre-align source to reference in mm world space via NIfTI affine
            4. Run TPS on pre-aligned landmark pairs

        Args:
            data_dir:     Root directory containing one sub-folder per patient ID
            reference_id: Patient ID string for the reference scan (e.g. "0004")
            source_id:    Patient ID string for the source scan (e.g. "0010")
            organ_label:  Voxel label value for liver in the liver mask
            alpha:        TPS regularization parameter
        """
        import os

        def load_patient(patient_id):
            base = os.path.join(data_dir, patient_id)

            liver, affine = self.load_segmentation_from_file(
                os.path.join(base, "liver.nii.gz")
            )
            portal, _ = self.load_segmentation_from_file(
                os.path.join(base, "portal_vein.nii.gz")
            )
            hepatic_vein, _ = self.load_segmentation_from_file(
                os.path.join(base, "liver_vessels.nii.gz")
            )

            segs = {}
            for i in range(1, 9):
                path = os.path.join(base, f"liver_segment_{i}.nii.gz")
                if os.path.exists(path):
                    seg_data, _ = self.load_segmentation_from_file(path)
                    segs[i] = seg_data

            return liver, portal, hepatic_vein, segs, affine

        print(f"\n--- Loading reference ({reference_id}) ---")
        ref_liver, ref_portal, ref_hepatic_vein, ref_segs, ref_affine = \
            load_patient(reference_id)

        print(f"\n--- Loading source ({source_id}) ---")
        src_liver, src_portal, src_hepatic_vein, src_segs, src_affine = \
            load_patient(source_id)

        print(f"\n--- Extracting reference landmarks ---")
        ref_landmarks = self.extract_anatomical_landmarks(
            ref_liver, ref_portal,
            segment_segs=ref_segs,
            hepatic_vein_seg=ref_hepatic_vein,
            organ_label=organ_label,
        )

        print(f"\n--- Extracting source landmarks ---")
        src_landmarks = self.extract_anatomical_landmarks(
            src_liver, src_portal,
            segment_segs=src_segs,
            hepatic_vein_seg=src_hepatic_vein,
            organ_label=organ_label,
        )

        if len(ref_landmarks) != len(src_landmarks):
            raise ValueError(
                f"Landmark count mismatch: {len(ref_landmarks)} ref "
                f"vs {len(src_landmarks)} src"
            )

        n_segs = len(ref_segs)
        print(f"\n--- Pre-aligning using {n_segs} Couinaud segment centroids ---")
        src_landmarks, R, t_src, t_ref, src_aff, ref_aff = \
            self._prealign_landmarks(
                src_landmarks, ref_landmarks,
                src_affine, ref_affine,
                n_segment_landmarks=n_segs,
            )
        self.prealign_R       = R
        self.prealign_t_src   = t_src
        self.prealign_t_ref   = t_ref
        self.prealign_src_aff = src_aff
        self.prealign_ref_aff = ref_aff
        self.ref_shape        = ref_liver.shape

        print(f"\n=== Building TPS from {len(ref_landmarks)} landmark pairs ===")
        self.mapper = NonRigidMapper3D(src_landmarks, ref_landmarks)

        coeffs = self.mapper.find_transformation(alpha=alpha)

        return coeffs
    
    # same thing here 
    def transform_segmentation(self, source_seg, coefficients):
        """
        Apply pre-alignment + TPS transformation to a segmentation volume.
        Uses nearest-neighbor interpolation for label preservation.
        
        Args:
            source_seg: Source segmentation volume
            coefficients: TPS transformation coefficients
            
        Returns:
            Transformed segmentation volume
        """
        print(f"Applying transformation to segmentation...")

        orig_voxels = np.argwhere(source_seg > 0)
        if len(orig_voxels) == 0:
            return source_seg

        print(f"  Transforming {len(orig_voxels):,} voxels...")

        nonzero_voxels = orig_voxels.astype(np.float32)

        # Convert to mm, apply Procrustes pre-alignment, convert back to ref voxel space.
        if self.prealign_R is not None:
            ones    = np.ones((len(nonzero_voxels), 1))
            mm_pts  = (self.prealign_src_aff @ np.hstack([nonzero_voxels, ones]).T).T[:, :3]
            mm_c    = mm_pts - self.prealign_t_src
            mm_rot  = (self.prealign_R @ mm_c.T).T + self.prealign_t_ref
            inv_ref = np.linalg.inv(self.prealign_ref_aff)
            ones2   = np.ones((len(mm_rot), 1))
            nonzero_voxels = (inv_ref @ np.hstack([mm_rot, ones2]).T).T[:, :3]

        transformed_voxels = self.mapper.transform_points(nonzero_voxels, coefficients)

        transformed_voxels = np.round(transformed_voxels).astype(np.int32)

        # Drop voxels with negative coordinates (outside any valid grid)
        valid_mask = np.all(transformed_voxels >= 0, axis=1)
        orig_voxels_v = orig_voxels[valid_mask]
        transformed_voxels_v = transformed_voxels[valid_mask]

        # Size the output to encompass all transformed voxels — at least as large
        # as ref_shape so the reference and transformed grids are comparable for Dice.
        if self.ref_shape is not None:
            out_shape = tuple(
                max(int(self.ref_shape[i]), int(transformed_voxels_v[:, i].max()) + 1)
                for i in range(3)
            )
        else:
            out_shape = tuple(int(transformed_voxels_v[:, i].max()) + 1 for i in range(3))

        transformed_seg = np.zeros(out_shape, dtype=source_seg.dtype)
        for i, orig_idx in enumerate(orig_voxels_v):
            transformed_seg[tuple(transformed_voxels_v[i])] = source_seg[tuple(orig_idx)]

        print(f"  Retained {np.sum(transformed_seg > 0):,} voxels")
        return transformed_seg


# Added this so that the program doesnt crash if it fails to loada file. essentialy just calls the 
# load segmentation from file fnc
def _try_load(registrator, path, label):
    try:
        arr, _ = registrator.load_segmentation_from_file(path)
        print(f"  {label}: loaded from {path}")
        return arr
    except Exception as e:
        print(f"  {label}: not found ({e})")
        return None


def _load_segments(registrator, data_dir, case_id):
    """Load Couinaud segments 1-8 for one case. Returns dict {1..8: array} or None."""
    segs = {}
    any_loaded = False
    for seg_idx in range(1, 9):

        # Layout: Data/<case_id>/liver_segment_<i>.nii.gz
        # if issues persist this may be wy
        nested_path = os.path.join(data_dir, case_id, f"liver_segment_{seg_idx}.nii.gz")

        if os.path.exists(nested_path):
            arr = _try_load(registrator, nested_path, f"  Segment {seg_idx}")

        if arr is not None:
            segs[seg_idx] = arr
            any_loaded = True
    return segs if any_loaded else None



if __name__ == "__main__":
    import os
    print("TotalSegmentator 3D Non-Rigid Registration Tool")
    print("=" * 60)

    registrator = TotalSegmentatorRegistration(organ_name="liver")

    coeffs = registrator.register(
        data_dir="Data",
        reference_id="0004",
        source_id="0010",
        alpha=0.05,
    )

    src_liver, src_affine = registrator.load_segmentation_from_file(
        "Data/0010/liver.nii.gz"
    )
    transformed = registrator.transform_segmentation(src_liver, coeffs)

    out = nib.Nifti1Image(transformed, registrator.prealign_ref_aff)
    nib.save(out, "Data/transformed_0010_to_0004.nii.gz")
    print("\nDone. Saved transformed_0010_to_0004.nii.gz")


    # Dice Correlation Coefficient — pads both arrays to a common bounding box
    # so different grid sizes don't cause broadcast errors.
    def dice(seg_a, seg_b, label=1):
        # added this padding function to essentially add zeros (empty space) around the shape of the 
        # object so that it doesnt need to cutt antying off to compare the two shapes. 
        out_shape = tuple(max(a, b) for a, b in zip(seg_a.shape, seg_b.shape))
        def pad_to(arr, shape):
            pad = [(0, shape[i] - arr.shape[i]) for i in range(arr.ndim)]
            return np.pad(arr, pad)
        a = pad_to(seg_a, out_shape) == label
        b = pad_to(seg_b, out_shape) == label
        intersection = np.logical_and(a, b).sum()
        denom = a.sum() + b.sum()
        return (2.0 * intersection) / denom if denom > 0 else 0.0

    from scipy.ndimage import zoom as nd_zoom
    ref_liver, _ = registrator.load_segmentation_from_file("Data/0004/liver.nii.gz")
    zoom_factors = tuple(r / s for r, s in zip(ref_liver.shape, src_liver.shape))
    src_liver_resampled = (nd_zoom(src_liver.astype(np.float32), zoom_factors, order=0) > 0.5).astype(src_liver.dtype)
    print(f"Dice before: {dice(ref_liver, src_liver_resampled):.4f}")
    print(f"Dice after:  {dice(ref_liver, transformed):.4f}")



# going to be updating all of this very soon with a much better pipeline, didnt mean for so many things to be outright
# made by claude but I would have automated tedious things like graphs/etc anyways.